### ISSUE TITLE
README Unclear

### ISSUE THREAD

**Issue by dragonrider7225** [tabatkins/wordle-list#1]
As written, the readme suggests any word that comes out of the grep could potentially be the solution. Something as simple as a statement that this is a list of valid *guesses* and that only a small portion of the list can actually be the solution would greatly clarify what this repository can and cannot be used for.

**Comment by tabatkins** [comment]
They could all be the solution. Limiting it to the actual answers list is cheating.

**Comment by dragonrider7225** [comment]
You seem to have misunderstood what I said. I suggested "a statement that this is a list of valid *guesses* and that only [about a sixth] of the list can actually be the solution" and from that you decided that I was saying that only the words that could be the solution should be included.

Also, you seem to have misunderstood the meaning of the word "solution". Each wordle puzzle has only one solution: the all-green word. All the other words are mere guesses.

**Comment by tabatkins** [comment]
No, they're all possible solutions unless you're cheating and relying on the foreknowledge that Wordle has a predefined list of about 2k answers. Without that inner knowledge that can only be obtained by peeping the source code, *any* five letter English word might be a solution. This repo is merely a list of such words. (For convenience, it's only the words that Wordle actually recognizes; there are potentially more very rare 5-letter words out there. But limiting the list in this way isn't cheating, as Wordle will tell you for free if a guess isn't in its list at all, so I'm just front-loading that work for you.)

Also tho, I'm not here to take someone unsuccessfully trying to be sarcastic about my reasonable and correct phrasing. Reexamine your life choices that led you to think that was a reasonable way to interact with a stranger on the Internet.
