### ISSUE TITLE
Missing words as of 7/27/2022

### ISSUE THREAD

**Issue by ChamiLamelas** [tabatkins/wordle-list#10]
This list is missing the following words: 
* agora
* pupal
* lynch

All three of these words seem to be in the Wordle "dictionary" of available words for two reasons: 

1. According to [this Medium article](https://medium.com/@owenyin/here-lies-wordle-2021-2027-full-answer-list-52017ee99e86) all three of these words have been answers to Wordle in the past.
2. [Wordle](https://www.nytimes.com/games/wordle/index.html) as of 7/27/2022 accepts all three of these words as valid guesses.

**Comment by tabatkins** [comment]
Ah, did they add those back? Those were removed in the great "kill some remaining offensive words" update when the NYT first took over. I'll check.

**Comment by tabatkins** [comment]
Huh, it looks like they just reverted all the removals? Fixed in 5c451721cb453d0355178571caac6053491bd620 based on what's currently available on the NYT website.

**Comment by ChamiLamelas** [comment]
Thank you!
