### ISSUE TITLE
new words being added?

### ISSUE THREAD

**Issue by bkaufx** [tabatkins/wordle-list#11]
Is this being kept current?  According to this a bunch of new words were just added.

https://www.reddit.com/r/wordle/comments/x3alye/nyt_added_1881_words_to_the_allowed_list/

**Comment by tabatkins** [comment]
I don't actively track it, but happy to update when changes are brought to my attention.

**Comment by tabatkins** [comment]
And done: <https://github.com/tabatkins/wordle-list/commit/c2bd6b43e6d78d39a6f87f5b3151d92de2716836>
