### ISSUE TITLE
grep exclude characters needs to be in quotes

### ISSUE THREAD

**Issue by BartmanEH** [tabatkins/wordle-list#13]
I had fun playing with your wordle list and culling it down with grep. It was a good exercise to learn a bit more about grep. However, in my mac terminal, I had to add quotes as follows:
`curl -s https://raw.githubusercontent.com/tabatkins/wordle-list/main/words | grep -v '[dukfiht]' | grep .r... | grep n | grep -v ...n. | grep g | grep -v ..g..`
...in order for the initial letter exclusions to work otherwise it threw an error:
`zsh: no matches found: [dukfiht]`
I really couldn't find much explanation for why I needed the quotes except for [this](https://unix.stackexchange.com/questions/630399/grep-use-square-brackets-to-match-specific-characters) which explains that the quotes protect the pattern from the shell interpreter.

Anyway, thought I might let you know in case you want to adjust your readme usage notes.

**Comment by tabatkins** [comment]
Not needed on bash, must be something specific to zsh expansions.

**Comment by BartmanEH** [comment]
FYI, I made a .zshrc config file with "setopt NO_NO_MATCH" in it and the requirement for the quotes went away ;-)
