### ISSUE TITLE
Does not contain all guess words

### ISSUE THREAD

**Issue by juleskuehn** [tabatkins/wordle-list#9]
Tested against the [original solutions list](https://medium.com/@owenyin/here-lies-wordle-2021-2027-full-answer-list-52017ee99e86), this is missing the solutions that were removed by NY Times:

{'agora', 'fibre', 'lynch', 'pupal', 'slave', 'wench'}

All of these are allowed entries in Wordle. I wonder if anything else is missing?

<img width="393" alt="Screen Shot 2022-05-22 at 12 13 39 PM" src="https://user-images.githubusercontent.com/1150048/169705108-0f302a2c-491f-4dd4-b156-355228ca9aaa.png">

**Comment by juleskuehn** [comment]
The correct solution and allowed word lists are in the source code here: https://www.nytimes.com/games/wordle/main.9622bc55.js

**Comment by tabatkins** [comment]
Yes, I removed the words that the NYT did in https://github.com/tabatkins/wordle-list/commit/12642a315d92f32366b9e44854074be3cccc6753

I haven't updated to the newer changes because this is an extremely low priority project for me. Feel free to PR.
